### ISSUE TITLE
c89mtx_unlock is always returning an error on pthread

### ISSUE THREAD

**Issue by edubart** [mackron/c89thread#2]
The function `c89mtx_unlock` is always returning an error on pthread due to a typo in its logic, these lines:
```c
    if (result == 0) {
        return c89thrd_error;
    }
```

it should have been actually `result != 0`

**Comment by mackron** [comment]
Thanks. Fixed.

Commit: https://github.com/mackron/c89thread/commit/6972868c1abc051ebb3442809aa92da6006fc70d
